"""todas las tablas

Revision ID: 2e9251715bf8
Revises: 
Create Date: 2024-03-17 22:17:26.099433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9251715bf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('p_total', sa.Integer(), nullable=False),
    sa.Column('p_actual', sa.Integer(), nullable=False),
    sa.Column('p_rezago', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h_brigadista_id', sa.Integer(), nullable=False),
    sa.Column('h_brigadista_name', sa.String(length=255), nullable=False),
    sa.Column('h_area_created_at', sa.DateTime(), nullable=True),
    sa.Column('h_area_id', sa.Integer(), nullable=False),
    sa.Column('h_area_p_total', sa.Integer(), nullable=False),
    sa.Column('h_area_p_actual', sa.Integer(), nullable=False),
    sa.Column('h_area_p_rezago', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('pwdhash', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('historial')
    op.drop_table('areas')
    # ### end Alembic commands ###
